name: Integration tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "27 4 * * *" # 4:27 every night
env:
  PSYNC_CONFIG_DIR: "./tests/data/integration_config"

jobs:
  test-notebooks:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --group test
      - name: Setup Spotify token
        env:
          SPOTIFY_TOKEN_JSON: ${{ secrets.SPOTIFY_TOKEN_JSON }}
        run: |
          mkdir -p $PSYNC_CONFIG_DIR
          echo "$SPOTIFY_TOKEN_JSON" > "$PSYNC_CONFIG_DIR/spotify_token.json"
      - name: Test spotify notebooks
        run: |
          uv run pytest --nbmake --nbmake-timeout=600 docs/services/spotify/*.ipynb
      - name: Setup Tidal token
        env:
          TIDAL_TOKEN_JSON: ${{ secrets.TIDAL_TOKEN_JSON }}
        run: |
          mkdir -p $PSYNC_CONFIG_DIR
          echo "$TIDAL_TOKEN_JSON" > "$PSYNC_CONFIG_DIR/tidal_token.json"
      - name: Test tidal notebooks
        run: |
          uv run pytest --nbmake --nbmake-timeout=600 docs/services/tidal/*.ipynb
