name: Python checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Get changed files and store them in outputs
  changed-files:
    runs-on: ubuntu-latest
    name: Get changed files
    outputs:
      any_python_changed: ${{ steps.raw-changed-python-files.outputs.any_changed }}
      changed_python_files: ${{ steps.changed-python-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed python files
        id: raw-changed-python-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.py
      - name: Check changed python files
        id: changed-python-files
        env:
          CHANGED_PYTHON_FILES: ${{ steps.raw-changed-python-files.outputs.all_changed_files }}
        run: |
          echo "all_changed_files=$CHANGED_PYTHON_FILES" >> "$GITHUB_OUTPUT"

  lint:
    name: Check style with Ruff
    runs-on: [self-hosted, linux]
    needs: changed-files
    if: needs.changed-files.outputs.any_python_changed == 'true'
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --group lint
      - name: Check style with Ruff
        run: |
          uv run ruff check --output-format=github .

  format:
    name: Check format with Ruff
    runs-on: [self-hosted, linux]
    needs: changed-files
    if: needs.changed-files.outputs.any_python_changed == 'true'
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --group lint
      - name: Check format with Ruff
        run: |
          uv run ruff format --check --diff .

  mypy:
    name: Check type hints with mypy
    runs-on: [self-hosted, linux]
    needs: changed-files
    if: needs.changed-files.outputs.any_python_changed == 'true'
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Check type hints with mypy
        run: |
          uv run mypy --show-error-codes --check-untyped-defs --config-file ./pyproject.toml ./
  test:
    name: Run tests
    runs-on: [self-hosted, linux]
    needs: changed-files
    if: needs.changed-files.outputs.any_python_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    env:
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --all-extras
          source .venv/bin/activate
      - name: Test with coverage
        run: |
          uv run pytest --cov=plistsync --cov-report xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy -v
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  docs:
    name: Build Sphinx docs
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
      - name: Install docs dependencies
        run: |
          uv sync --group docs
      - name: Build Sphinx docs
        run: |
          cd docs
          uv run sphinx-build -b html . _build/html -W --keep-going -j auto
